# Generated by Django 4.2.7 on 2023-11-13 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='respone',
            new_name='response',
        ),
    ]
