# Generated by Django 4.2.7 on 2023-11-13 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_rename_respone_chat_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='condition',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
