# Generated by Django 4.2.7 on 2023-11-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_remove_chat_interaction_time_chat_statement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='statement',
            field=models.CharField(default='1', max_length=255),
        ),
    ]
